name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🔍 Lint (ESLint)
        run: npm run lint

      - name: 🏗️ Build de l’application
        run: npm run build

      - name: 🐳 Build de l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taskmaster-pro:latest .

      - name: 🔐 Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📤 Push vers Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/taskmaster-pro:latest
